FROM node:22.17.0
WORKDIR /usr/local/app
RUN npm install --audit false --fund false -g npm@11.4.2
COPY ./package.json .
COPY ./package-lock.json .
RUN npm ci --ignore-scripts --audit false --fund false
COPY . .
EXPOSE 5173
CMD ["npx", "vite", "--port", "5173"]
